# Explanation: https://jupyterbook.org/en/stable/customize/config.html
# Book settings
title                       : Data Mining  # The title of the book. Will be placed in the left navbar.
author                      : John Samuel  # The author of the book
copyright                   : "2021"  
logo                        : "datamining.svg"  
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : false

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true  # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  latex_documents:
    targetname: book.tex

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/johnsamuelwrites/DataMining  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

